services:
  server:
    image: 'website:latest'
    ports:
      - '8000:8000'
    environment: {}
    networks:
      - edge
    develop:
      watch:
        - path: website/server
          target: /app/server
          action: sync
        - path: website/content
          target: /app/content
          action: sync
networks:
  edge:
    external: true
