services:
  git-sync:
    image: 'git-sync:latest'
    ports:
      - '8080:8080'
    environment:
      SYNC_DEST: /data
      REPOS: >-
        [{"id":"docs","repo":"ritajhq/ensemble","ref":"main","path":"docs"},{"id":"docs","repo":"ritajhq/ensemble","ref":"main","path":"docs",
        "trigger":"manual"}]
      WEBHOOK_SECRET_DOCS: '${DOCS_WEBHOOK_SECRET}'
    networks:
      - edge
    volumes:
      - 'docs-content:/data'
    develop:
      watch:
        - path: git-sync
          target: /app
          action: sync
  server:
    image: 'website:latest'
    ports:
      - '8000:8000'
    environment: {}
    networks:
      - edge
    volumes:
      - 'docs-content:/data:ro'
    develop:
      watch:
        - path: website/server
          target: /app/server
          action: sync
        - path: website/content
          target: /app/content
          action: sync
volumes:
  docs-content: {}
networks:
  edge:
    external: true
