release:
  server:
    kit: docker

deploy:
  compute:
    app:
      type: container-orchestrated
      image: ${release.server.image}
      replicas: 1
      env:
        ENSEMBLE_WORKSPACE: /data
      ports:
        http: 8787
      health:
        path: /v1/debug
        interval: 10
        timeout: 3
      mounts:
        - storage: state
          path: /data
      development:
        sync:
          - app: server
            path: /app/server

  storage:
    state:
      type: file-storage
