jobs:
  pack:
    steps:
      - name: build_server
        run: |
          echo "Building..."
          ens build server

      - name: compile_cli
        run: |
          echo "Compiling..."
          ens pack cli deno.compile 

      - name: pack_server
        run: |
          echo "Packing..."
          ens pack -o ensemble/server server docker

      - name: publish_web
        run: |
          mc alias set release-bucket https://s3.ritaj.app "$S3_ACCESS_KEY" "$S3_SECRET_KEY"
          mc cp --recursive source/artifacts/web "release-bucket/release/ensemble/web/latest/"

      - name: tag_and_push
        run: |
          echo "Tagging and pushing..."
          docker image tag ensemble/server:latest registry.ritaj.app/ensemble/server:latest
          docker push registry.ritaj.app/ensemble/server:latest