# yaml-language-server: $schema=https://raw.githubusercontent.com/ritajhq/ensemble/main/.ensemble/schemas/workflow.schema.json
# yaml-embedded-languages: shell

on:
  - manual:
      inputs:
        - name: job
          type: job
          default: [server]
          display: "Job to run"

context:
  secrets:
    - name: REGISTRY_USERNAME
      default: ''
    - name: REGISTRY_PASSWORD
      default: ''

resources:
  repositories:
    ensemble:
      url: https://github.com/ritajhq/ensemble.git

jobs:
  cli:
    in:
      repository: ensemble
    steps:
      - name: compile_cli
        run: |
          echo "Compiling..."
          ens pack cli deno.compile

  hot-server:
    in:
      repository: ensemble
    steps:
      - name: pack_hot-server
        run: |
          echo "Packing..."
          ens pack hot-server docker

      - name: tag_and_push
        run: |
          echo "Tagging and pushing..."
          docker image tag hot-server:latest registry.ritaj.app/hot-server:latest

          docker login registry.ritaj.app -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

          docker push registry.ritaj.app/hot-server:latest

  server:
    needs: [cli]
    in:
      repository: ensemble
    steps:
      - name: build_server
        run: |
          echo "Building..."
          ens build -m production server

      - name: pack_server
        run: |
          echo "Packing..."
          ens pack -o ensemble/server server docker

      - name: tag_and_push
        run: |
          echo "Tagging and pushing..."
          docker image tag ensemble/server:latest registry.ritaj.app/ensemble/server:latest

          docker login registry.ritaj.app -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

          docker push registry.ritaj.app/ensemble/server:latest

  web:
    needs: [hot-server]
    in:
      repository: ensemble
    steps:
      - name: build_web
        run: |
          echo "Building..."
          ens build -m production web

      - name: pack_web
        run: |
          echo "Packing..."
          ens pack -o ensemble/web web docker

      - name: tag_and_push
        run: |
          echo "Tagging and pushing..."
          docker image tag ensemble/web:latest registry.ritaj.app/ensemble/web:latest

          docker login registry.ritaj.app -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

          docker push registry.ritaj.app/ensemble/web:latest

  runner:
    needs: [cli]
    in:
      repository: ensemble
    steps:
      - name: pack_runner
        run: |
          echo "Packing..."
          ens pack -o ensemble/runner runner docker

      - name: tag_and_push
        run: |
          echo "Tagging and pushing..."
          docker image tag ensemble/runner:latest registry.ritaj.app/ensemble/runner:latest

          docker login registry.ritaj.app -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

          docker push registry.ritaj.app/ensemble/runner:latest