# yaml-language-server: $schema=https://raw.githubusercontent.com/ritajhq/ensemble/main/.ensemble/schemas/workflow.schema.json

on:
  - manual:
      inputs:
        - name: message
          display: Message
          type: string

jobs:
  demo:
    steps:
      - name: print_message
        run: |
          echo "${{ trigger.message }}"
          sleep 5

      - name: confirm_success
        run: echo "Demo workflow completed successfully."
