# yaml-language-server: $schema=https://raw.githubusercontent.com/ritajhq/ensemble/main/.ensemble/schemas/workflow.schema.json

resources:
  repositories:
    ensemble:
      url: https://github.com/ritajhq/ensemble.git

jobs:
  dev:
    steps:
      - name: build_web_once
        in:
          repository: ensemble
        run: |
          set -euo pipefail
          ens build web

      - name: pack_server_image
        in:
          repository: ensemble
        run: |
          set -euo pipefail
          ens build server
          ens pack cli deno.compile
          ens pack server docker

      - name: pack_hot_server_image
        in:
          repository: ensemble
        run: |
          set -euo pipefail
          ens pack hot-server docker

      - name: watch_and_serve
        in:
          repository: ensemble
        run: |
          set -euo pipefail

          export ENSEMBLE_HOST_WORKFLOWS_PATH="${{ repositories.ensemble.path }}/workflows/local/workspace/workflows"
          export DOCKER_GID="$(getent group docker | cut -d: -f3)"

          ens build web --watch &
          build_web_pid=$!
          ens build server --watch &
          build_server_pid=$!

          trap 'kill "$build_web_pid" "$build_server_pid" 2>/dev/null; docker compose -f workflows/local/docker-compose.yml down' EXIT

          docker compose -f workflows/local/docker-compose.yml up --watch
