build:
  cli:
    kit: deno.bundle
  demo/spa:
    kit: react
  website/content:
    kit: react
    target: ssr
  website/server:
    kit: deno.bundle
meta:
  ship:
    demo/spa:
      artifacts:
        - demo/spa
    website:
      artifacts:
        - website/content
        - website/server
hooks:
  release:
    after: >-
      git-cliff --tag "$ENSEMBLE_RELEASE_TAG" -o CHANGELOG.md && { git diff
      --quiet -- CHANGELOG.md || git commit CHANGELOG.md -m "chore(changelog):
      update for $ENSEMBLE_RELEASE_TAG"; }
